In [3116]:
import pandas as pd
import numpy as np

In [3117]:
# Función sigmoide y su derivada
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [3119]:
def linear_error(y_true, y_pred):
     return np.mean(y_true - y_pred)

def cross_entropy_loss(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-9))

def mean_absolute_error(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

def binary_crossentropy(y_true, y_pred):
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [3120]:
def initialize_weights(input_size, output_size):
    weights = np.random.randn(input_size, output_size) * 0.01
    bias = np.zeros((1, output_size))
    return weights, bias

In [3121]:
def forward_pass(X, weights, bias):
    z = np.dot(X, weights) + bias
    return sigmoid(z)

In [3122]:
def backpropagation(X, y, output, weights, bias, learning_rate):
    # Calcular el error
    error = output - y
    
    # Calcular los gradientes
    d_weights = np.dot(X.T, error * sigmoid_derivative(output))
    d_bias = np.sum(error * sigmoid_derivative(output), axis=0, keepdims=True)
    
    # Actualizar pesos y sesgos
    weights -= learning_rate * d_weights
    bias -= learning_rate * d_bias

    return weights, bias

In [3123]:
def train(X, y, input_size, output_size, epochs, learning_rate):
    # Inicializar pesos y sesgos
    weights, bias = initialize_weights(input_size, output_size)
    
    # Entrenar por varias épocas
    for epoch in range(epochs):
        # Propagación hacia adelante
        output = forward_pass(X, weights, bias)
        
        # Calcular pérdida
        loss = binary_crossentropy(y, output)
        
        # Retropropagación
        weights, bias = backpropagation(X, y, output, weights, bias, learning_rate)
        
        # Imprimir el progreso cada 100 épocas
        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return weights, bias

In [3124]:
# Predicción
def predict(X, weights, bias):
    output = forward_pass(X, weights, bias)
    return (output > 0.3).astype(int)

In [3125]:
#x = ([precio,metroscuadrados,pisomarmol,pisomadera,hornoagas,hornoelectrico])
#y = ([moderna,rustica,barata])

# X = np.array([
#     [150000, 120, 1, 0, 1, 0],
#     [80000, 80, 0, 1, 0, 1],
#     [200000, 150, 1, 1, 1, 1],
#     [50000, 60, 0, 0, 0, 1],
#     [120000, 100, 1, 0, 1, 0]
# ])


# y = np.array([
#     [1, 0, 0],
#     [0, 1, 1],
#     [1, 0, 0],
#     [0, 1, 1],
#     [1, 0, 0] 
# ])


In [3126]:
dataset = pd.read_csv("ev_charging_patterns.csv")
dataset = dataset.dropna()
dataset = dataset.drop(columns=['User ID', 'Charging Station ID', 'Charging Station Location','Charging Start Time','Charging End Time','Time of Day','Day of Week','Charger Type'])
dataset.head(1)

Vehicle Model  Battery Capacity (kWh)  Energy Consumed (kWh)  \
0        BMW i3              108.463007              60.712346   

   Charging Duration (hours)  Charging Rate (kW)  Charging Cost (USD)  \
0                   0.591363           36.389181            13.087717   

   State of Charge (Start %)  State of Charge (End %)  \
0                  29.371576                86.119962   

   Distance Driven (since last charge) (km)  Temperature (°C)  \
0                                293.602111         27.947953   

   Vehicle Age (years) User Type  
0                  2.0  Commuter

In [3127]:
X = dataset.drop('User Type', axis=1)
X = pd.get_dummies(X, drop_first=False).astype(int).to_numpy()

y = dataset['User Type']
y= pd.get_dummies(y, drop_first=False).astype(int).to_numpy()
y

array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [3128]:
# Parámetros
input_size = X.shape[1]
output_size = y.shape[1]
epochs = 10000
learning_rate = 0.001

In [3129]:
# Entrenar el modelo

weights, bias = train(X, y, input_size, output_size, epochs, learning_rate)

Epoch 0, Loss: 1.1673
Epoch 100, Loss: 6.9071
Epoch 200, Loss: 6.9071
Epoch 300, Loss: 6.9071
Epoch 400, Loss: 6.9071
Epoch 500, Loss: 6.9071


C:\Users\Usuario\AppData\Local\Temp\ipykernel_50332\626581559.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Epoch 600, Loss: 6.9071
Epoch 700, Loss: 6.9071
Epoch 800, Loss: 6.9071
Epoch 900, Loss: 6.9071
Epoch 1000, Loss: 6.9071
Epoch 1100, Loss: 6.9071
Epoch 1200, Loss: 6.9071
Epoch 1300, Loss: 6.9071
Epoch 1400, Loss: 6.9071
Epoch 1500, Loss: 6.9071
Epoch 1600, Loss: 6.9071
Epoch 1700, Loss: 6.9071
Epoch 1800, Loss: 6.9071
Epoch 1900, Loss: 6.9071
Epoch 2000, Loss: 6.9071
Epoch 2100, Loss: 6.9071
Epoch 2200, Loss: 6.9071
Epoch 2300, Loss: 6.9071
Epoch 2400, Loss: 6.9071
Epoch 2500, Loss: 6.9071
Epoch 2600, Loss: 6.9071
Epoch 2700, Loss: 6.9071
Epoch 2800, Loss: 6.9071
Epoch 2900, Loss: 6.9071
Epoch 3000, Loss: 6.9071
Epoch 3100, Loss: 6.9071
Epoch 3200, Loss: 6.9071
Epoch 3300, Loss: 6.9071
Epoch 3400, Loss: 6.9071
Epoch 3500, Loss: 6.9071
Epoch 3600, Loss: 6.9071
Epoch 3700, Loss: 6.9071
Epoch 3800, Loss: 6.9071
Epoch 3900, Loss: 6.9071
Epoch 4000, Loss: 6.9071
Epoch 4100, Loss: 6.9071
Epoch 4200, Loss: 6.9071
Epoch 4300, Loss: 6.9071
Epoch 4400, Loss: 6.9071
Epoch 4500, Loss: 6.9071
Epoc

In [3130]:
predictions = predict(X, weights, bias)
print("Predicciones:")
print(predictions)

# Salidas reales para comparación
print("Salidas reales:")
print(y)

Predicciones:
[[0 1 0]
 [0 1 0]
 [0 1 0]
 ...
 [0 1 0]
 [0 1 0]
 [0 1 0]]
Salidas reales:
[[0 1 0]
 [1 0 0]
 [0 1 0]
 ...
 [0 1 0]
 [0 1 0]
 [0 1 0]]


C:\Users\Usuario\AppData\Local\Temp\ipykernel_50332\626581559.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
