In [16]:
import pandas as pd
import numpy as np

In [17]:
# Función sigmoide y su derivada
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [18]:
def linear_error(y_true, y_pred):
     return np.mean(y_true - y_pred)

def cross_entropy_loss(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-9))

def mean_absolute_error(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

def binary_crossentropy(y_true, y_pred):
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [19]:
def initialize_weights(input_size, output_size):
    weights = np.random.randn(input_size, output_size) * 0.01
    bias = np.zeros((1, output_size))
    return weights, bias

In [20]:
def forward_pass(X, weights, bias):
    z = np.dot(X, weights) + bias
    return sigmoid(z)

In [21]:
def backpropagation(X, y, output, weights, bias, learning_rate):
    # Calcular el error
    error = output - y
    
    # Calcular los gradientes
    d_weights = np.dot(X.T, error * sigmoid_derivative(output))
    d_bias = np.sum(error * sigmoid_derivative(output), axis=0, keepdims=True)
    
    # Actualizar pesos y sesgos
    weights -= learning_rate * d_weights
    bias -= learning_rate * d_bias

    return weights, bias

In [34]:
def train(X, y, input_size, output_size, epochs, learning_rate):
    # Inicializar pesos y sesgos
    weights, bias = initialize_weights(input_size, output_size)
    
    # Entrenar por varias épocas
    for epoch in range(epochs):
        # Propagación hacia adelante
        output = forward_pass(X, weights, bias)
        
        # Calcular pérdida
        # loss = binary_crossentropy(y, output)
        loss = linear_error(y, output)
        
        # Retropropagación
        weights, bias = backpropagation(X, y, output, weights, bias, learning_rate)
        
        # Imprimir el progreso cada 100 épocas
        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return weights, bias

In [31]:
# Predicción
def predict(X, weights, bias):
    output = forward_pass(X, weights, bias)
    # return (output > 0.3).astype(int)
    return output

In [24]:
#x = ([precio,metroscuadrados,pisomarmol,pisomadera,hornoagas,hornoelectrico])
#y = ([moderna,rustica,barata])

# X = np.array([
#     [150000, 120, 1, 0, 1, 0],
#     [80000, 80, 0, 1, 0, 1],
#     [200000, 150, 1, 1, 1, 1],
#     [50000, 60, 0, 0, 0, 1],
#     [120000, 100, 1, 0, 1, 0]
# ])


# y = np.array([
#     [1, 0, 0],
#     [0, 1, 1],
#     [1, 0, 0],
#     [0, 1, 1],
#     [1, 0, 0] 
# ])


In [25]:
dataset = pd.read_csv("ev_charging_patterns.csv")
dataset = dataset.dropna()
dataset = dataset.drop(columns=['User ID', 'Charging Station ID', 'Charging Station Location','Charging Start Time','Charging End Time','Time of Day','Day of Week','Charger Type'])
dataset.head(1)

Vehicle Model  Battery Capacity (kWh)  Energy Consumed (kWh)  \
0        BMW i3              108.463007              60.712346   

   Charging Duration (hours)  Charging Rate (kW)  Charging Cost (USD)  \
0                   0.591363           36.389181            13.087717   

   State of Charge (Start %)  State of Charge (End %)  \
0                  29.371576                86.119962   

   Distance Driven (since last charge) (km)  Temperature (°C)  \
0                                293.602111         27.947953   

   Vehicle Age (years) User Type  
0                  2.0  Commuter

In [26]:
X = dataset.drop('User Type', axis=1)
X = pd.get_dummies(X, drop_first=False).astype(int).to_numpy()

y = dataset['User Type']
y= pd.get_dummies(y, drop_first=False).astype(int).to_numpy()
y

array([[0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [36]:
from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit_transform(X)
y = StandardScaler().fit_transform(y)

In [45]:
# Parámetros
input_size = X.shape[1]
output_size = y.shape[1]
epochs = 30000
learning_rate = 0.001

In [46]:
# Entrenar el modelo

weights, bias = train(X, y, input_size, output_size, epochs, learning_rate)

Epoch 0, Loss: -0.5000
Epoch 100, Loss: -0.0964
Epoch 200, Loss: -0.0809
Epoch 300, Loss: -0.0742
Epoch 400, Loss: -0.0698
Epoch 500, Loss: -0.0668
Epoch 600, Loss: -0.0647
Epoch 700, Loss: -0.0631
Epoch 800, Loss: -0.0619
Epoch 900, Loss: -0.0610
Epoch 1000, Loss: -0.0601
Epoch 1100, Loss: -0.0593
Epoch 1200, Loss: -0.0585
Epoch 1300, Loss: -0.0577
Epoch 1400, Loss: -0.0571
Epoch 1500, Loss: -0.0564
Epoch 1600, Loss: -0.0558
Epoch 1700, Loss: -0.0553
Epoch 1800, Loss: -0.0548
Epoch 1900, Loss: -0.0544
Epoch 2000, Loss: -0.0540
Epoch 2100, Loss: -0.0536
Epoch 2200, Loss: -0.0533
Epoch 2300, Loss: -0.0530
Epoch 2400, Loss: -0.0527
Epoch 2500, Loss: -0.0525
Epoch 2600, Loss: -0.0523
Epoch 2700, Loss: -0.0521
Epoch 2800, Loss: -0.0519
Epoch 2900, Loss: -0.0517
Epoch 3000, Loss: -0.0515
Epoch 3100, Loss: -0.0513
Epoch 3200, Loss: -0.0511
Epoch 3300, Loss: -0.0509
Epoch 3400, Loss: -0.0508
Epoch 3500, Loss: -0.0506
Epoch 3600, Loss: -0.0504
Epoch 3700, Loss: -0.0503
Epoch 3800, Loss: -0.050

In [47]:
predictions = predict(X, weights, bias)
print("Predicciones:")
print(predictions)

# Salidas reales para comparación
print("Salidas reales:")
print(y)

Predicciones:
[[3.02518597e-05 1.31612343e-05 8.06829534e-09]
 [1.02211656e-05 1.63787339e-10 1.08499694e-08]
 [4.10442173e-08 5.73587078e-07 5.08031308e-04]
 ...
 [8.99696629e-12 4.38920823e-08 5.70991155e-10]
 [4.84776924e-12 9.86409933e-01 1.99757672e-04]
 [2.25590526e-13 5.16016814e-19 5.95498256e-09]]
Salidas reales:
[[-0.66390084  1.34145628 -0.71274119]
 [ 1.50624903 -0.74545851 -0.71274119]
 [-0.66390084  1.34145628 -0.71274119]
 ...
 [-0.66390084  1.34145628 -0.71274119]
 [-0.66390084  1.34145628 -0.71274119]
 [-0.66390084  1.34145628 -0.71274119]]


In [48]:
mse = np.mean((y - predictions) ** 2)
mse

0.9684802423180792